version: "3"
services:
  app:
    build:
      context: .
    container_name: app
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: >
      sh -c "python3 manage.py wait_for_db &&
             python manage.py migrate"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=app
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    depends_on:
      - db
  db:
    image: "postgres:14-alpine"
    container_name: db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=app
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"