name: Test

on:
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    services:
      db:
        image: postgres:14
        env:
          POSTGRES_DB: app
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set Up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Wait for PostgreSQL to start
        run: |
          while ! nc -z localhost 5432; do
            echo "Waiting for PostgreSQL to start..."
            sleep 5
          done

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run flake8
        run: flake8

      - name: Run tests
        run: python manage.py test
