name: Test

on:
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    services:
      db:
        image: postgres:14
        env:
          POSTGRES_DB: app
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set Up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Wait for PostgreSQL to start
        run: |
          while ! nc -z localhost 5432; do
            echo "Waiting for PostgreSQL to start..."
            sleep 5
          done

      - name: Build and run Docker containers for GitHub
        run: docker-compose -f docker-compose.github.yml up --build -d

      - name: Run flake8
        run: docker exec -i app flake8

      - name: Run books tests. Test model
        run: docker exec -i app python manage.py test books.tests.test_book_model

      - name: Run books tests. Test AnonimUserPermissions
        run: docker exec -i app python manage.py test books.tests.test_book_view_permissions.AnonimUserPermissions

      - name: Run books tests. Test AdminUserPermissions
        run: docker exec -i app python manage.py test books.tests.test_book_view_permissions.AdminUserPermissions

      - name: Run books tests. Test AuthenticatedUserPermissions
        run: docker exec -i app python manage.py test books.tests.test_book_view_permissions.AuthenticatedUserPermissions
